package org.example.enums;

public enum Commands {

    NEWLEAD, SHOWLEADS, SHOWOPPORTUNITIES, SHOWACCOUNTS, LOOKUPLEAD, LOOKUPOPPORTUNITY, LOOKUPACCOUNT, CONVERT, CLOSED_WON, CLOSED_LOST, HELP, EXIT

}
